spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.db}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: ${mysql.user}
    password: ${mysql.password}
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 2000
      testWhileIdle: true

  devtools:
    restart:
      enabled: false
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

server:
  port: 8888

# 是否开始swagger 线上配置false
swagger:
  enable: true
